roboclaw_wrapper:
  ros__parameters:
    drive_acceleration_factor: 0.02  # fraction used to scale the drive motor acceleration (0, 1]
    corner_acceleration_factor: 0.8  # fraction used to scale the corner motor acceleration (0, 1])
    velocity_timeout: 2  # maximum time [s] a particular velocity command will stay active without a new command before stopping
    baud_rate: 115200
    device: "/dev/serial1"
    addresses: [128, 129, 130]
    roboclaw_mapping:
      # gear ratio is approx 172, exact value is 171.79 though
      drive_left_front:
        address: 128
        channel: M1
        ticks_per_rev: 48
        gear_ratio: 171.79
      drive_left_middle:
        address: 128
        channel: M2
        ticks_per_rev: 48
        gear_ratio: 171.79
      drive_left_back:
        address: 129
        channel: M2
        ticks_per_rev: 48
        gear_ratio: 171.79
      drive_right_back:
        address: 129
        channel: M1
        ticks_per_rev: 48
        gear_ratio: 171.79
      drive_right_middle:
        address: 130
        channel: M2
        ticks_per_rev: 48
        gear_ratio: 171.79
      drive_right_front:
        address: 130
        channel: M1
        ticks_per_rev: 48
        gear_ratio: 171.79
